language: node_js
node_js:
    - "8"
cache:
    yarn: true
    directories:
        - node_modules
install:
    - yarn
    - npm i -g codecov
before_script:
    - tsc | exit 0
script:
    - yarn test
after_script:
    - codecov
