@startuml

database ServiceStore <<JSON>>
database AccountStore <<JSON>>

participant Store <<(S, #ADD182)Singleton>>
participant Service <<(F, #ADD182)Function>>
participant Provider <<(C,#ADD1B2)Class>>
participant "Dynamizr/SchemaCreator" as schemaCreator <<(C, #ADD182)Static Class>>

Store -> ServiceStore : get services
ServiceStore -> Store : push services array
group each [Service Array]
    Store -> Service: ServiceStoreを送信
    alt providerがarrayの場合mapを用いてProviderの配列を生成する
        Service -> Provider: request\ncreate instance
        alt All Unit schema has dynamized
            Provider -> Provider: Parse
            Provider -> Service: return Provider Instance
            else Unit schema has'nt dynamized
                group each [Unit objects]
                    Provider -> schemaCreator: Send Schema Data
                    schemaCreator -> Provider: return dynaschema
                end
            Provider -> Service: return Provider Instance
        end
    end
    Service -> Store: return Provider Instance
end

@enduml
